### ISSUE TITLE
Fix output `data.frame` for checking issues.

### ISSUE THREAD

**Issue by SimonGoring** [gvaldez17/quad_checking#5]
Currently the output of `checkgml` is two `data.frame`s, bound in a list.  The first is `geo` and the second is `tests`.  We have two issues we want to fix.
1.  The identifiability of points: When we export points, both to ArcGIS for visual checks against the original scanned quad sheets, and to the csv files for data entry and correction, it's not entirely clear which points match between the CSV and the SHP file.  This should be corrected since at lines 17 and 33 of `gmltoR.R` the coordinates are assigned to the `geo` `data.frame`.
2.  Added tests.  There are several new tests identified by @gvaldez17, these need to be added into the `tests` `data.frame`, both at line 35 (where the tests need to be written as the boolean expressions), and at line 18, where the column name (test name) is added, but assigned an NA.

**Comment by gvaldez17** [comment]
1) I am unsure as to what I should add on lines 17 and 33, what am I trying to add to correct this problem?

2) have correctly added the extra tests & aded a test name + NA in the section after line 18.
 do not need help here

**Comment by gvaldez17** [comment]
1) I am unsure as to what I should add on lines 17 and 33, what am I trying to add to correct this problem?

2) have correctly added the extra tests & added a test name = NA in the section after line 18.
do not need help here

**Comment by SimonGoring** [comment]
1. Sorry, I meant that this was corrected earlier, not that something needed to be corrected.
2.  Great!
