### ISSUE TITLE
potential tests

### ISSUE THREAD

**Issue by gvaldez17** [gvaldez17/quad_checking#6]
Theses are two other tests I wrote but am unsure if I should add them because I don't know if they make sense or if they have errors in them.

1) test to see if there is no species 1 name, but there is a dist or diameter
noname1 = is.na(map@data$species1) & (!is.na(map@data$dist1) | !is.na(map@data$diam1))

2) test to see if there is no species 2 name, but there is a dist or diameter
noname2 = is.na(map@data$species2) & (!is.na(map@data$dist2) | !is.na(map@data$diam2))

**Comment by SimonGoring** [comment]
This test:

``` r
noname1 = is.na(map@data$species1) & (!is.na(map@data$dist1) | !is.na(map@data$diam1))
```

tells me you're looking for NA species identifiers with declared diameters or distances.

``` r
noname2 = is.na(map@data$species2) & (!is.na(map@data$dist2) | !is.na(map@data$diam2))
```

Same, but for species 2.  You could combine these:

``` r
noname =  is.na(map@data$species1) & (!is.na(map@data$dist1) | !is.na(map@data$diam1)) | is.na(map@data$species2) & (!is.na(map@data$dist2) | !is.na(map@data$diam2))
```

using the `|` "or" operator.  So that noname is basically `noname1 | noname2`
